### ISSUE TITLE
KnowCoder的Eval方面的问题

### ISSUE THREAD

**Issue by ZhenbinChan** [ICT-GoKnow/KnowCoder#4]
我想在我自己的数据集上重新评估KnowCoder的性能，但是在eval的代码中，我发现需要ontology_dir，请问这个文件夹需要什么文件呢？如果可以，还请作者新增对于eval的使用说明在ReadMe中，非常感谢！

**Comment by Starry-Liu1** [comment]
Ontology文件用来从WikiData中找到预测出实体类型的上位概念，如果上位概念中的类型与Ground Truth一致，我们认为预测正确。

感谢您的反馈，我们会补充一个下载链接。

**Comment by zig-kwin-hu** [comment]
您好，请问ontology的下载链接是什么呢？

**Comment by Starry-Liu1** [comment]
您可以从这个链接下载onto_data文件夹，https://pan.baidu.com/s/1rYPqyWHz_1gyG4nR09lmtA。  提取码：4k97

**Comment by luwry** [comment]
提取码：4k97 错误？

**Comment by Starry-Liu1** [comment]
之前的链接可能过期了，请使用下面的链接：
链接: https://pan.baidu.com/s/1O7SefggOysqt3aInfuaPOQ 提取码: g4aj





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年3月19日(星期三) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ICT-GoKnow/KnowCoder] KnowCoder的Eval方面的问题 (Issue #4)












   
提取码：4k97 错误？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  luwry left a comment (ICT-GoKnow/KnowCoder#4)
 
提取码：4k97 错误？

**Comment by Starry-Liu1** [comment]
之前的链接可能过期了，请使用下面的链接：
链接: https://pan.baidu.com/s/1O7SefggOysqt3aInfuaPOQ 提取码: g4aj

**Comment by luwry** [comment]
ok,thanks！
